apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devopscanvas-portal.fullname" . }}
  labels:
    {{- include "devopscanvas-portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "devopscanvas-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devopscanvas-portal.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: portal-content
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          env:
            - name: NODE_ENV
              value: "production"
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "devopscanvas-portal.fullname" . }}-config
        - name: portal-content
          configMap:
            name: {{ include "devopscanvas-portal.fullname" . }}-config